name: KONG

env:
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}
  test_client_key: ${{ secrets.KONG_CLIENT_SDK_KEY }}
  repo_pat: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
  FORCE_COLOR: true

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  KONG:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Get KONG
        run: |
          git clone https://oauth2:$repo_pat@github.com/statsig-io/kong.git .

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Deps
        run: npm install

      - name: Setup Python SDK
        run: npm run kong -- setup python -v

      - name: Build Bridge
        run: npm run kong -- build python -v

      - name: Run Tests
        run: npm run kong -- test python -v -r

      - name: Run Measure Base Benchmark Score 
        if: github.ref == 'refs/heads/main'
        run: npm run kong -- regression_test python -p base -v

      - name: Upload base benchmark score
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: python-perf
          path: /tmp/perf/python_perf_score.txt
          retention-days: 5

      - name: Run regression test
        if: github.ref != 'refs/heads/main'
        run: npm run kong -- regression_test python -p test -v
